name: testing
on: [push, pull_request]
jobs:
    golangci-lint-check:
        name: golangci-lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v1
              with:
                  go-version: 1.14
            - name: Add $GOPATH/bin
              run: |
                  echo ::add-path::$(go env GOPATH)/bin

            - uses: actions/checkout@v2

            - name: Install linters
              run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8

            - name: Run lint
              env:
                  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                golangci-lint run

    go-testing:
        name: go-testing
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v1
              with:
                  go-version: 1.14
            - name: Add $GOPATH/bin
              run: |
                  echo ::add-path::$(go env GOPATH)/bin

            - uses: actions/checkout@v2

            - name: testing
              run: make test

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  flags: unittests
                  fail_ci_if_error: true
