name: testing
on: [push, pull_request]
jobs:
    go-testing:
        name: go-testing
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v1
              with:
                  go-version: 1.14
            - name: Add $GOPATH/bin
              run: |
                  echo ::add-path::$(go env GOPATH)/bin

            - uses: actions/checkout@v2

            - name: testing
              run: make go-test
